htm_params:
  tm:
    cellsPerColumn: 32
    activationThreshold: 13
    initialPerm: 0.21
    permanenceConnected: 0.5
    minThreshold: 10
    newSynapseCount: 20
    permanenceInc: 0.1
    permanenceDec: 0.1
    predictedSegmentDecrement: 0.0
    maxSegmentsPerCell: 128
    maxSynapsesPerSegment: 32

  anomaly_likelihood:
    learningPeriod: 150
    estimationSamples: 50
    historicWindowSize: 1000
    reestimationPeriod: 30
    averagingWindow: 3
